config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :restaurants do
    resources :reviews, only: [:new, :create ]
  end

  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # dependent: :destroy will make sure that reviews will also be deleted when you delete the restaurant
  has_many :reviews, dependent: :destroy

  # cannot be blank
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :restaurant, only: %i[show update destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
    # check private method and before_action
    @restaurant
  end

  def new
    # instantiate, info is nil
    @restaurant = Restaurant.new
    # use raise here to check
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    # check private method and before_action
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :address, :phone_number)
  end

  def restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # restaurant_id is the restaurant id found in the review table
    @restaurant = Restaurant.find(params[:restaurant_id])
    # instantiate
    @review = Review.new
  end

  def create
    # create responds to a button click in the form
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params) # why new instead of create?
    @review.restaurant_id = @restaurant.id
    if @review.save
      redirect_to restaurant_path(@restaurant.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    # why no permission for delete like create?
    review = Review.find(params[:id])
    review.destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    redirect_to restaurant_path(@restaurant.id)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>List of Restaurants</h1>

<ul>
  <%@restaurants.each do |restaurant| %>
  <li><%= link_to restaurant.name, restaurant_path(restaurant.id) %></li>
  <% end %>
</ul>

<%= link_to "Add Restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Create New Restaurant</h1>

<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.input :phone_number %>
  <%= f.submit %>
<% end %>

<p class="mt-3"><%= link_to "Restaurants List", restaurants_path %></p>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p>Cuisine: <%= @restaurant.category %></p>
<p>Address: <%= @restaurant.address %></p>
<p>Contact: <%= @restaurant.phone_number %></p>

<p><strong>Reviews</strong></p>

<% @restaurant.reviews.each do |review| %>
<ul>
    <li>
    <%= review.content %> ||
    <%= review.rating %> star ||
    <%= link_to "Delete",review_path(review.id),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%> ||
    </li>
</ul>
<% end %>
<p><%= link_to "Add Review",  new_restaurant_review_path(@restaurant.id )%></p>
<p><%= link_to "Delete Restaurant", @restaurant, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}  %></p>
<p><%= link_to "Restaurants List", restaurants_path %></p>

app/views/reviews/new.html.erb
<h1>Review for <%= @restaurant.name %></h1>
<!--[@restaurant, @review] is writen in order of the path(restaurants/id/review)
Also, it is written like this because @review is nested in restaurant -->
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
   <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

<p><%= link_to "Back", restaurant_path(@restaurant.id) %></p>